= Contract with souvenir NFT

Smart contract used as souvenir NFT for participating in the Barcelona DevCentralized workshop (https://github.com/andrzej-casper/pixel-rate[PixelRate application]). It is entirely based on https://github.com/casper-ecosystem/cep-78-enhanced-nft[CEP-78].

[NOTE]
.Relevant testnet details
====
* Contract deploy hash: https://testnet.cspr.live/deploy/f7a902b600e24089a4cdeb383b7aae989e798006d68b7adbbbf40eae8d077a3c[f7a902b600e24089a4cdeb383b7aae989e798006d68b7adbbbf40eae8d077a3c]
* Contract package hash: https://testnet.cspr.live/contract-package/07edc543bf31adc4a1ece3f8622ef44153316e1639cb6badebad0367a52b8804[07edc543bf31adc4a1ece3f8622ef44153316e1639cb6badebad0367a52b8804]
* Hash - version 1: https://testnet.cspr.live/contract/c4f6b9af763a2728378d850ddd51100deb2c95a40fee0c4744cee470e28a081c[c4f6b9af763a2728378d850ddd51100deb2c95a40fee0c4744cee470e28a081c]
====

== Requirements

* curl
* tar
* casper-client

== Usage

[INFO]
====
We are using CEP-78 modalities, so we can rely on pre-compiled contract, instead of coding it on our own.
====

. Get compiled contract from release page:
+
[source,bash]
----
$ curl --silent --location https://github.com/casper-ecosystem/cep-78-enhanced-nft/releases/download/v1.3.0/cep-78-wasm.tar.gz \
  | tar xvz -C ./cep-78
----

. Deploy our custom configured NFT to network (cost: ~260 CSPR):
+
[NOTE]
====
In the following examples we will be:

* Using *CLI client* to operate - it can be installed with `$ cargo install casper-client`.
* Operating in test chain called *testnet* - specifed in `--chain-name` parameter.
* Sending commands to the one of https://testnet.cspr.live/tools/peers[connected peers] - specified in `--node-address` argument.
* Identify with *account keys* located under `~/wallets/07_alice/` - they were generated with `casper-client keygen [PATH]`.
====
+
[source,bash]
----
$ casper-client put-deploy \
  --id 1 \
  --node-address http://135.181.216.142:7777 \
  --chain-name casper-test \
  --payment-amount 312000000000 \
  --secret-key ~/wallets/07_alice/secret_key.pem \
  --session-path ./cep-78/contract.wasm \
  --session-arg "collection_name:string='devcentralized_barcelona_2023'" \
  --session-arg "collection_symbol:string='DEVC_BCN_2023'" \
  --session-arg "total_token_supply:u64='8'" \
  --session-arg "ownership_mode:u8='1'" \
  --session-arg "nft_kind:u8='2'" \
  --session-arg "nft_metadata_kind:u8='0'" \
  --session-arg "identifier_mode:u8='0'" \
  --session-arg "metadata_mutability:u8='0'" \
  --session-arg "minting_mode:u8='0'" \
  --session-arg "events_mode:u8='2'" \
  --session-arg "owner_reverse_lookup_mode:u8='0'"
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "f7a902b600e24089a4cdeb383b7aae989e798006d68b7adbbbf40eae8d077a3c"
  }
}
----

. Getting contract hash:
+
[TIP]
====
Make sure you have `jq` tool installed, as it will be used for JSON parsing. Otherwise you can supply values manually.
====
+
[source,bash]
----
$ STATE_ROOT_HASH=`casper-client get-state-root-hash \
  --id 2 \
  --node-address http://135.181.216.142:7777 \
  | jq -r .result.state_root_hash`
$ casper-client query-global-state \
  --id 3 \
  --node-address http://135.181.216.142:7777 \
  --state-root-hash ${STATE_ROOT_HASH} \
  --key ~/wallets/07_alice/public_key_hex \
  | jq -r ".result.stored_value.Account.named_keys[] | select(.name == \"cep78_contract_package_devcentralized_barcelona_2023\") | .key"
hash-691c5d3789896a66458bbf0decf3ac96e067af0453ccffe7fe295e5b244010b9
----

. Minting NFT (cost: ~11 CSPR):
+
[NOTE]
====
* You can customize NFT `name`, which is passed in token metadata.

* Image in below example - `token_uri` - was created using https://nightcafe.studio[NightCafe] and stored in IPFS using https://www.pinata.cloud[Pinata]; `checksum` is sha256 hash of that file. You can also find it in this repository at `./souvenir.jpg`.
====
+
[source,bash]
----
$ casper-client put-deploy \
  --id 4 \
  --node-address http://135.181.216.142:7777 \
  --chain-name casper-test \
  --payment-amount 22000000000 \
  --secret-key ~/wallets/07_alice/secret_key.pem \
  --session-package-hash hash-691c5d3789896a66458bbf0decf3ac96e067af0453ccffe7fe295e5b244010b9 \
  --session-entry-point "mint" \
  --session-arg "token_owner:key='account-hash-7188948fdc3d97a762fcd62f8b17ef128e5d38d09ce535cc97df3c5931369b90'" \
  --session-arg "token_meta_data:string='{\"name\":\"[DevCentralized] Casper Workshop Attendee Souvenir NFT\",\"token_uri\": \"https://pin.ski/3C0VedZ\",\"checksum\":\"456050015873156be7d815b11dc0edf065828052f630de3e9d6c011806568631\"}'"
{
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "bc140e454376cc67ebd612f8f4a0c0191e8a8a6d80aae7eb6ab7cb0239c0af00"
  }
}
----
