= Contract with souvenir NFT

Smart contract used as souvenir NFT for participating in the Barcelona DevCentralized workshop (https://github.com/andrzej-casper/pixel-rate[PixelRate application]). It is entirely based on https://github.com/casper-ecosystem/cep-78-enhanced-nft[CEP-78].

[NOTE]
.Relevant testnet details
====
* Contract deploy hash: https://testnet.cspr.live/deploy/c0b7a2f99746e69b14949a1d924787a8469c7010387d982ce59a8de4b1ae0ff2[c0b7a2f99746e69b14949a1d924787a8469c7010387d982ce59a8de4b1ae0ff2]
* Contract package hash: https://testnet.cspr.live/contract-package/07edc543bf31adc4a1ece3f8622ef44153316e1639cb6badebad0367a52b8804[07edc543bf31adc4a1ece3f8622ef44153316e1639cb6badebad0367a52b8804]
* Hash - version 1: https://testnet.cspr.live/contract/c4f6b9af763a2728378d850ddd51100deb2c95a40fee0c4744cee470e28a081c[c4f6b9af763a2728378d850ddd51100deb2c95a40fee0c4744cee470e28a081c]
====

== Requirements

* curl
* tar
* casper-client

== Usage

[INFO]
====
We are using CEP-78 modalities, so we can rely on pre-compiled conract, instead of coding it on our own.
====

. Get compiled contract from release page:
+
[source,bash]
----
$ curl --silent --location https://github.com/casper-ecosystem/cep-78-enhanced-nft/releases/download/v1.3.0/cep-78-wasm.tar.gz \
  | tar xvz - -C ./cep-78
----

. Deploy our custom configured NFT to network (cost: ~260 CSPR):

[source,bash]
----
$ casper-client put-deploy \
  --id 1 \
  --node-address http://135.181.216.142:7777 \
  --chain-name casper-test \
  --payment-amount 312000000000 \
  --secret-key ~/wallets/07_alice/secret_key.pem \
  --session-path ./cep-78/contract.wasm \
  --session-arg "collection_name:string='devcentralized_barcelona_2023'" \
  --session-arg "collection_symbol:string='DEVC_BCN_2023'" \
  --session-arg "total_token_supply:u64='32'" \
  --session-arg "ownership_mode:u8='1'" \
  --session-arg "nft_kind:u8='2'" \
  --session-arg "nft_metadata_kind:u8='3'" \
  --session-arg "json_schema:string='{\"properties\":{\"user_message\":{\"name\":\"user_message\",\"description\":\"A message attached by the user.\",\"required\":true}}}'" \
  --session-arg "identifier_mode:u8='0'" \
  --session-arg "metadata_mutability:u8='0'" \
  --session-arg "minting_mode:u8='0'" \
  --session-arg "owner_reverse_lookup_mode:u8='0'"
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "c0b7a2f99746e69b14949a1d924787a8469c7010387d982ce59a8de4b1ae0ff2"
  }
}
----

. Getting contract hash:
+
[TIP]
====
Make sure you have `jq` tool installed, as it will be used for JSON parsing. Otherwise you can supply values manually.
====
+
[source,bash]
----
$ STATE_ROOT_HASH=`casper-client get-state-root-hash \
  --id 2 \
  --node-address http://135.181.216.142:7777 \
  | jq -r .result.state_root_hash`
$ casper-client query-global-state \
  --id 3 \
  --node-address http://135.181.216.142:7777 \
  --state-root-hash ${STATE_ROOT_HASH} \
  --key ~/wallets/07_alice/public_key_hex \
  | jq -r ".result.stored_value.Account.named_keys[] | select(.name == \"cep78_contract_package_devcentralized_barcelona_2023\") | .key"
hash-07edc543bf31adc4a1ece3f8622ef44153316e1639cb6badebad0367a52b8804
----

. Minting NFT (cost: ~3 CSPR):
+
[NOTE]
====
* Replace `token_owner` value in `--session-arg` with the account hash that you want to own the new NFT.
* Make sure you supplied contract's package hash to `--session-package-hash` parameter, along with `hash-` prefix.
* You can customize `user_message`, which is passed as token metadata.
====
+
[source,bash]
----
$ casper-client put-deploy \
  --id 4 \
  --node-address http://135.181.216.142:7777 \
  --chain-name casper-test \
  --payment-amount 4500000000 \
  --secret-key ~/wallets/07_alice/secret_key.pem \
  --session-package-hash hash-07edc543bf31adc4a1ece3f8622ef44153316e1639cb6badebad0367a52b8804 \
  --session-entry-point "mint" \
  --session-arg "token_owner:key='account-hash-7188948fdc3d97a762fcd62f8b17ef128e5d38d09ce535cc97df3c5931369b90'" \
  --session-arg "token_meta_data:string='{\"user_message\": \"My first NFT! An exciting step in my digital journey.\"}'"
{
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "api_version": "1.4.15",
    "deploy_hash": "e3dadd7ffaa6ae9bae9372fbba4d96939256bdfdf8dfc85d44dc4c7f07f2f6f0"
  }
}
----
